# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6458227b967a311cefe16059102fc653b3e582b40729165f436ecae0416245c790e20869e83717b16ee80f6784fe18016cfc4f5aeefd23bad8788f9a036c5318

test:
  secret_key_base: 17ab156bda5d4ab4b53359a437e59740419c1cf0c8739a39231f788cb087117a0956632ae2ba3a24fc498054170a73d3f0a77e4ad08e4343e418a8669ac93f6f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
